### ISSUE TITLE
Selected Radio button is not readable. Text is not Visible

### ISSUE THREAD

**Issue by YasarArafathAli** [MetaVASP/Zipify#13]
![image](https://user-images.githubusercontent.com/60683319/155476021-8fec4e95-9674-4d8a-8fc5-769541362932.png)

**Comment by HarshKumarChoudary** [comment]
I would like to work in this issue under GSSOC'22. Please assign it to me. I would create a PR after 1 march.

**Comment by Tapabrata-Goswami** [comment]
Can I work on it right now??

**Comment by Tapabrata-Goswami** [comment]
@YasarArafathAli I think it is all right see this, button is working ------>>
![12](https://user-images.githubusercontent.com/89471881/155885111-479d7ae4-72ba-4570-bd98-4270c35f64b1.png)

**Comment by pulkit-30** [comment]
> ![image](https://user-images.githubusercontent.com/60683319/155476021-8fec4e95-9674-4d8a-8fc5-769541362932.png)

Hey @YasarArafathAli ,
I think you are using a dark-mode chrome extension

**Comment by YasarArafathAli** [comment]
Yeah my bad
