### ISSUE TITLE
docs: Add Code of Conduct

### ISSUE THREAD

**Issue by Pradumnasaraf** [MetaVASP/Zipify#17]
### Changes
- Add official `CODE_OF_CONDUCT.md` (provided by GitHub)

#### Due to that we are also missing out on some checks on the community guidelines checklist

![Screenshot from 2022-03-01 23-23-27](https://user-images.githubusercontent.com/51878265/156222564-c3cf8613-8ada-4e2c-9c4f-19d078abd2d7.png)

#### Contribution towards GSsoc`22, Thank you

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.
