### ISSUE TITLE
Logo update

### ISSUE THREAD

**Issue by priyanshi1282** [MetaVASP/Zipify#29]
#### We can update Logo of Zipify.
Click here to  <a href="https://www.canva.com/design/DAE6NQzspSw/QRG4xR4FrO1xcAN0B97mxA/view?utm_content=DAE6NQzspSw&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton" >See Logo</a> (swipe to see more).
If you like any logo, we can adjust color of logo accordingly.
<b>I would love to contribute under GSSoC'22.</b>
@pulkit-30 Please review once and let me know 😃.

**Comment by pulkit-30** [comment]
https://www.canva.com/design/DAE1xahIAf8/T-o86ZTnA65dVYtTCpgiXA/view?utm_content=DAE1xahIAf8&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton&mode=preview
Sharing the logo template come up with some modifications in this one
Verify me, Is the link working?

**Comment by priyanshi1282** [comment]
yes, link is working.
so I have to add logos designed by me in this given link, right?

**Comment by pulkit-30** [comment]
yep! add them and share the `edit` link here

**Comment by priyanshi1282** [comment]
https://www.canva.com/design/DAE6TtXfJsE/share/preview?token=DvbYwVTNqVsqer5_xy4qvQ&role=EDITOR&utm_content=DAE6TtXfJsE&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

Edit link for the same.

**Comment by pulkit-30** [comment]
Thanks 👍🏽

**Comment by bhutani2002** [comment]
> I have added new ones, Please Mind having a look
> 
> @MetaVASP/assist-team

![Zipify logo-1](https://user-images.githubusercontent.com/84590758/157098725-1ec617d6-5a15-463b-b533-2aec847d6263.png)
![Zipify logo-2](https://user-images.githubusercontent.com/84590758/157098733-4115e09e-ec37-45e9-abf8-96d9b6460d25.png)

For me, both of these look good👌👍

**Comment by pulkit-30** [comment]
Lets change logo to [this one](https://user-images.githubusercontent.com/84590758/157098733-4115e09e-ec37-45e9-abf8-96d9b6460d25.png)

@priyanshi1282 download png or svg image file and then change the previous one with this....

**Comment by priyanshi1282** [comment]
Ok sure 😀

**Comment by priyanshi1282** [comment]
@pulkit-30 I tried to update the logo image but the output showing is not updated one.
I have run the project as you directed, npm install >> npm start >> http://localhost (on chrome)

![code](https://user-images.githubusercontent.com/88632352/159153568-60b0a930-c136-4686-98c1-bbf999f49a39.png)

![live](https://user-images.githubusercontent.com/88632352/159153577-23f0555d-4ac1-4b95-b47c-346aea7b8b21.png)

**Comment by pulkit-30** [comment]
Using the command `npm start` or `node app.js` start the dev server @ localhost:80, when you do some changes, you need to stop the server and restart the server.

stopping and restarting the server is very hectic, for every small change you need to stop and restart the server again n again, 
I recommend using `npx nodemon`,  to start the development server, which will show changes in the browser without stoping and restarting the server, you just need to save your changes and refresh the browser tab.

**Comment by priyanshi1282** [comment]
@pulkit-30 It's working, Thanks 😀

**Comment by priyanshi1282** [comment]
#### Hey @pulkit-30 , you did not give any level mark to this contribution, hence it's not showing on my leaderboard.
Can you please look into this.

**Comment by pulkit-30** [comment]
@priyanshi1282 in think `gssoc22 ` label is sufficient. 
I have added the same label on your PR

**Comment by priyanshi1282** [comment]
Actually the contribution is not showing on leaderboard, hence the points to it are also not given.
![image](https://user-images.githubusercontent.com/88632352/161391004-d1f055c9-68ed-4c54-8e9d-617bc42b76ca.png)

**Comment by pulkit-30** [comment]
@Ayush7614
