### ISSUE TITLE
Add Issue+PR Templates

### ISSUE THREAD

**Issue by Ayush7614** [MetaVASP/Zipify#3]
Create a custom Issue and Pull Request Template.

Make an Issue Template. Any new Contributor must be able to specify if it is a new script or enhancement to an older one. It should also be specified which language he is coding it in.

Make a Pull Request Template. Any new Contributor must be able to specify if he has met all the requirements like Clean Code, proper README and Documentation, Screenshots (If any) attached and more.

**Comment by HarshKumarChoudary** [comment]
I would like to work on this issue. If this is for GSOOC 22 please assign it to me.

**Comment by AMGOcyber123** [comment]
I would like to work on this issue for GSSOC 22

**Comment by Ayush7614** [comment]
@HarshKumarChoudary @AMGOcyber123 already the pr is for this issue
