### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by Ayush7614** [MetaVASP/Zipify#4]
Create Contributors Guideline to help new Contributors get started with this Project.

Add a CONTRIBUTING.md to allow new users to get started with knowing how to contribute.
Add Screenshots wherever possible.
Add the basic information about creating Issues, Pull Requests and Branching.
Mention tutorials related to Git and Github to help them better understand.

**Comment by YasarArafathAli** [comment]
@pulkit-30 , Can I work on this one?

**Comment by pulkit-30** [comment]
yes
