### ISSUE TITLE
Create separate setup.md file

### ISSUE THREAD

**Issue by pulkit-30** [MetaVASP/Zipify#7]

**Comment by YasarArafathAli** [comment]
Hey @pulkit-30, I want to work on this issue. Thanks

**Comment by pulkit-30** [comment]
Sure,
I mentioned the steps for setting up the project in readme.md , You need to write them in a separate `setup.md` file.

**Comment by YasarArafathAli** [comment]
Thank you so much :), Can you assign it to me

**Comment by YasarArafathAli** [comment]
hey @pulkit-30  I have created a pull request :)
