### ISSUE TITLE
Modify readme.md

### ISSUE THREAD

**Issue by pulkit-30** [MetaVASP/Zipify#9]
more structured and well-written doc

**Comment by livealvi** [comment]
Hello,

How Can I Help You?
**_- On MARKDOWN / README_**

**Comment by pulkit-30** [comment]
Hey @livealvi ,

You can start with setting up the project and use that(just to get familiar ) and after that start writing about the project... what the user experience with this...
Like what are advantages and disadvantages ... 
secondly, it will be great and helpful if you present some logo design for this project (Zipify) and update the gifs and images ... all that stuff
last, you can add link for setup.md, and contributing.md in the readme file

**Comment by livealvi** [comment]
Thanks for replying @pulkit-30  🌟 

I need **more info** about your project.
Do you have any word files or other draft documents? like:
- _about advantages and disadvantages_ 
- testing unit

I know MARKDOWN syntaxes. And I can make that very well. I need info unless I **can’t start** MARKDOWN. I know this project (Zipify) about **Online File Compressor**  but Don’t know about full details or project goal.

**Comment by livealvi** [comment]
Hey @pulkit-30,

Please check the **pull request**
